// <auto-generated />
namespace FinalProject_OOD_2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PetData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PetData));
        
        string IMigrationMetadata.Id
        {
            get { return "202204242049233_PetData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
